"""add trend-tracking columns to team_histories

Revision ID: 15a37f291e46
Revises: 16a84a1b6810
Create Date: 2026-08-07 01:07:35.348973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a37f291e46'
down_revision: Union[str, Sequence[str], None] = '16a84a1b6810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_histories', sa.Column('over_performer_id', sa.String(length=32), nullable=True))
    op.add_column('team_histories', sa.Column('over_performer_delta', sa.Float(), nullable=True))
    op.add_column('team_histories', sa.Column('under_performer_id', sa.String(length=32), nullable=True))
    op.add_column('team_histories', sa.Column('under_performer_delta', sa.Float(), nullable=True))
    op.add_column('team_histories', sa.Column('margin', sa.Float(), nullable=True))
    op.add_column('team_histories', sa.Column('bench_beat_starter', sa.Integer(), nullable=True))
    op.add_column('team_histories', sa.Column('all_play_wins', sa.Integer(), nullable=True))
    op.add_column('team_histories', sa.Column('all_play_losses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_histories', 'all_play_losses')
    op.drop_column('team_histories', 'all_play_wins')
    op.drop_column('team_histories', 'bench_beat_starter')
    op.drop_column('team_histories', 'margin')
    op.drop_column('team_histories', 'under_performer_delta')
    op.drop_column('team_histories', 'under_performer_id')
    op.drop_column('team_histories', 'over_performer_delta')
    op.drop_column('team_histories', 'over_performer_id')
    # ### end Alembic commands ###
