"""add projeciton_cache table

Revision ID: 16a84a1b6810
Revises: e20388aa0f8c
Create Date: 2026-08-06 17:02:12.650243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a84a1b6810'
down_revision: Union[str, Sequence[str], None] = 'e20388aa0f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projection_cache',
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('season', 'week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projection_cache')
    # ### end Alembic commands ###
