"""added team_projected_pts and team_projected_delta to TeamHistory

Revision ID: 3b864fe1af7d
Revises: 15a37f291e46
Create Date: 2026-09-13 04:26:33.318766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b864fe1af7d'
down_revision: Union[str, Sequence[str], None] = '15a37f291e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_histories', sa.Column('team_projected_pts', sa.Float(), nullable=True))
    op.add_column('team_histories', sa.Column('team_projection_delta', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_histories', 'team_projection_delta')
    op.drop_column('team_histories', 'team_projected_pts')
    # ### end Alembic commands ###
