"""add over/under performer projected columns, clear stale projection data

Revision ID: a1fb355c0ee8
Revises: 3b864fe1af7d
Create Date: 2026-09-14 01:01:41.333309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1fb355c0ee8'
down_revision: Union[str, Sequence[str], None] = '3b864fe1af7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_histories', sa.Column('over_performer_projected', sa.Float(), nullable=True))
    op.add_column('team_histories', sa.Column('under_performer_projected', sa.Float(), nullable=True))

    op.execute("DELETE FROM team_histories")
    op.execute("DELETE FROM matchups")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_histories', 'under_performer_projected')
    op.drop_column('team_histories', 'over_performer_projected')
    # ### end Alembic commands ###
