"""create initial tables

Revision ID: e20388aa0f8c
Revises: 
Create Date: 2026-08-05 16:08:35.389128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20388aa0f8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_summaries',
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('week_generated', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('league_id', 'week_generated')
    )
    op.create_table('matchups',
    sa.Column('matchup_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('matchup_week', sa.Integer(), nullable=False),
    sa.Column('user_id_1', sa.String(length=64), nullable=False),
    sa.Column('user_id_2', sa.String(length=64), nullable=False),
    sa.Column('user_1_points', sa.Float(), nullable=False),
    sa.Column('user_2_points', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('matchup_id'),
    sa.UniqueConstraint('league_id', 'matchup_week', 'user_id_1', 'user_id_2')
    )
    op.create_table('team_histories',
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('matchup_week', sa.Integer(), nullable=False),
    sa.Column('high_performer_id', sa.String(length=32), nullable=True),
    sa.Column('high_performer_pts', sa.Float(), nullable=True),
    sa.Column('low_performer_id', sa.String(length=32), nullable=True),
    sa.Column('low_performer_pts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('league_id', 'user_id', 'matchup_week')
    )
    # ### end Alembic commands ###

    # ### Team Specific Results View ###
    op.execute("""
            CREATE VIEW TeamWeekResults AS
            SELECT league_id, matchup_week, user_id_1 AS user_id, user_id_2 AS opponent_user_id,
                   user_1_points AS points_scored, user_2_points AS points_allowed
            FROM matchups
            UNION ALL
            SELECT league_id, matchup_week, user_id_2 AS user_id, user_id_1 AS opponent_user_id,
                   user_2_points AS points_scored, user_1_points AS points_allowed
            FROM matchups
        """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_histories')
    op.drop_table('matchups')
    op.drop_table('league_summaries')
    # ### end Alembic commands ###

    op.execute("DROP VIEW TeamWeekResults")
